ViewPager装载几个Fragment时，由于ViewPager的缓存机制，会同时加载相邻的Fragment，这里举例有三个fragment：FragmentA、FragmentB和FragmentC，
首先会执行FragmentA的setUserVisibleHint方法，参数为false，然后执行FragmentB的setUserVisibleHint方法参数为false，接着执行FragmentA的setUserVisibleHint
方法，这时参数为true， onAttach——>onCreate，然后执行FragmentB的这两个方法，接着执行FragmentA的生命周期到onResume，FragmentB的生命周期方法到onResume。
切换到FragmentB，执行FragmentC的setUserVisibleHint方法，参数为false，执行FragmentA的setUserVisibleHint方法，参数为false，执行FragmentB
的setUserVisibleHint方法，参数为true，这时不再执行FragmentB的onResume之前（包括）的方法，执行FragmentC的生命周期方法到onResume。切换到FragmentC，执行
FragmentB的setUserVisibleHint方法，参数为false，执行FragmentC的方法setUserVisibleHint，参数为true，这里同理不执行FragmentC的onResume之前（包括）
的方法，执行销毁FragmentA的方法。
